name: Auto Deploy to cPanel

on:
  push:
    branches:
      - main # or your default branch

jobs:
  ftp-deploy:
    name: 📦 Deploy Laravel to cPanel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp # or sftp
          server-dir: ${{ secrets.FTP_TARGET }}
          local-dir: ./
